name: Trigger auto deployment for container-app-5k6up7o36csv6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '//**'
    - '.github/workflows/container-app-5k6up7o36csv6-AutoDeployTrigger-367192c4-3861-4f4e-9453-25fa5afb2b92.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP5K6UP7O36CSV6_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP5K6UP7O36CSV6_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP5K6UP7O36CSV6_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP5K6UP7O36CSV6_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP5K6UP7O36CSV6_REGISTRY_PASSWORD }}
          containerAppName: container-app-5k6up7o36csv6
          resourceGroup: reactbasicb5078666
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


